version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://asanabridge:asanabridge_pass@db:5432/asanabridge
      - JWT_SECRET=dev_jwt_secret_key_32_chars_minimum_for_testing
      - ASANA_CLIENT_ID=your_asana_client_id
      - ASANA_CLIENT_SECRET=your_asana_client_secret
      - ASANA_REDIRECT_URI=http://localhost:3000/api/oauth/asana/callback
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    command: >
      sh -c "npx prisma migrate deploy &&
             npx prisma generate &&
             npm start"

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=asanabridge
      - POSTGRES_PASSWORD=asanabridge_pass
      - POSTGRES_DB=asanabridge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U asanabridge"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Development database admin interface
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ADMINER_DEFAULT_SERVER=db

volumes:
  postgres_data: