name: Deploy to DigitalOcean

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Navigate to app directory
          cd /var/www/asanabridge
          
          # Backup production environment file
          cp .env .env.backup 2>/dev/null || true
          
          # Pull latest code
          git pull origin main
          
          # Restore production environment file
          cp .env.backup .env 2>/dev/null || true
          
          # Install dependencies
          npm ci
          
          # Build application
          npm run build
          
          # Remove dev dependencies after build
          npm ci --production
          
          # Run database migrations
          npx prisma migrate deploy
          
          # Restart application with PM2
          pm2 restart asanabridge || pm2 start dist/server.js --name asanabridge
          
          # Save PM2 configuration
          pm2 save

    - name: Deploy OmniFocus Agent
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Navigate to agent directory
          cd /var/www/asanabridge/omnifocus-agent
          
          # Install agent dependencies
          npm ci
          
          # Build agent
          npm run build
          
          # Remove dev dependencies after build
          npm ci --production
          
          # Restart agent with PM2
          pm2 restart omnifocus-agent || pm2 start dist/agent.js --name omnifocus-agent
          
          # Save PM2 configuration
          pm2 save

    - name: Health Check
      run: |
        sleep 30
        curl -f https://asanabridge.com/health || exit 1